
project_id = "evtlahgiyytcvfeiqwaz"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[storage]
enabled = true

[edge_functions]
[edge_functions.send-confirmation-email]
verify_jwt = false

[edge_functions.send-welcome-email]
verify_jwt = false

[edge_functions.create-user]
verify_jwt = false

