
project_id = "evtlahgiyytcvfeiqwaz"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[storage]
enabled = true

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_expiry = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[realtime]
enabled = true

[studio]
port = 54323

[inbucket]
enabled = true
port = 54324

[functions]
port = 54325
function_timeout_seconds = 60
[functions.update-crypto-prices]
verify_jwt = false
