
project_id = "evtlahgiyytcvfeiqwaz"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[functions]
serve_port = 54328

[functions.send-telegram-notification]
verify_jwt = false

[functions.simple-telegram-alert]
verify_jwt = false

[functions.lead-form-notification]
verify_jwt = false

[edge_functions.send-confirmation-email]
verify_jwt = false

[edge_functions.send-welcome-email]
verify_jwt = false

[edge_functions.create-user]
verify_jwt = false

[functions.send-telegram-notification]
memory_size = 128
timeout = 30

[functions.simple-telegram-alert]
memory_size = 128
timeout = 30

[functions.lead-form-notification]
memory_size = 128
timeout = 30
