// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qowgxvovtlkzsftanssa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvd2d4dm92dGxrenNmdGFuc3NhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NDIwMTIsImV4cCI6MjA2MzMxODAxMn0.XwLqnsoBu6c1jReaAZooF3-gr-w1GJCRrRsUlAyUt4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);