
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evtlahgiyytcvfeiqwaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2dGxhaGdpeXl0Y3ZmZWlxd2F6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MDcxNTUsImV4cCI6MjA2MjQ4MzE1NX0.W2M4_bOxvylAyWWAJKI2DWGfjZEXA7NsMpeALz1qX34";
const SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2dGxhaGdpeXl0Y3ZmZWlxd2F6Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NjkwNzE1NSwiZXhwIjoyMDYyNDgzMTU1fQ.dJutvbFHRlZGgzNrXxZ4j9bMV5U6EvFE233FLCiR9JI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Configure the client with explicit auth options for better session persistence
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY, 
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storage: localStorage
    }
  }
);

// Service role client for admin operations
export const supabaseAdmin = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_SERVICE_ROLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storage: localStorage
    }
  }
);
