// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evtlahgiyytcvfeiqwaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2dGxhaGdpeXl0Y3ZmZWlxd2F6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MDcxNTUsImV4cCI6MjA2MjQ4MzE1NX0.W2M4_bOxvylAyWWAJKI2DWGfjZEXA7NsMpeALz1qX34";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);